### ISSUE TITLE
Feature name BalanceRatioSelector not implemented

### ISSUE THREAD

**Issue by liuxiangdi** [ros-drivers/flir_camera_driver#30]
hi, thanks for your driver, it works well when i get the stereo camera video stream.

But when i change the image_color_coding to BayerRG8, i met this error
`[ERROR] [1562752443.834753711]: [SpinnakerCamera]: (18012381) Feature name BalanceRatioSelector not implemented.
`
I can change this value to get the right color image in spinview, how can I fix that?

**Comment by vSensorRT** [comment]
in the configuration file Spinnaker.cfg
change "auto_white_balance" to Once or Continuous.

# White Balance
gen.add("auto_white_balance",                    str_t,       SensorLevels.RECONFIGURE_RUNNING,     "White Balance compensates for color shifts caused by different lighting conditions.",                "Once")

**Comment by ghost** [comment]
Good catch, but this parameter could have been changed in your launch file rather than changing the default in the cfg file.
